{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autobreadboard.fullname" . }}
  labels:
    {{- include "autobreadboard.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
